//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    //this is required for imageupload file property
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class fighters
    {
        public int StylesID { get; set; }
        public int fighterID { get; set; }
       
        public string about { get; set; }
        public string image { get; set; }
     
        [DisplayName("Video eg. 6jaHyyi3m30")]
        public string video { get; set; }
     
        [RegularExpression(@"^\d{2}-\d{2}-\d{1}$", ErrorMessage = "Please enter fighters wins-loses-no contests.")]
        [Display(Prompt = "00-00-0")]
        public string records { get; set; }
        public string style { get; set; }
        public string weightclass { get; set; }
        public string recent { get; set; }
        public Nullable<int> likes { get; set; }


        public virtual styles styles { get; set; }
        //the following proprety is added to upload image
        public HttpPostedFileBase ImageFile { get; set; }
        //after the above, go to view, using razer, add the <input type="file" name="ImageFile" required>
    }
}
